### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by DocJade** [cubedhuang/nimi.li#10]
Having a setting to automatically focus the search bar when you open the website would be nice!
I usually open nimi.li just to find the definition for a single word quickly, having to click the search bar is a tad annoying.
I would put in a pull request but I'm not familiar with web dev sadly :P

**Comment by cubedhuang** [comment]
good add!

i also made it so that if the search bar isn't focused but you type anyway, it'll focus the search bar automatically
