### ISSUE TITLE
luka pona?

### ISSUE THREAD

**Issue by eightbitgiraffe** [cubedhuang/nimi.li#11]
nimi.li displays sitelen pona forms of every word, and the old nimi Linku spread sheet contains gifs for the luka pona forms of different words. Would it be possible to get those luka pona gifs to appear in nimi.li? This would make learning luka pona slightly easier, and it's something that I already want to learn. I would implement this myself as a PR, but I'm not familiar at all with the inner workings of nimi.li.

**Comment by cubedhuang** [comment]
luka pona exists on individual pages for existing words if you click the "more" button. Later today I can add it to the word popup to make it easier to access. I'll also experiment with using luka pona as a glyph display option, but it might be too small.

**Comment by eightbitgiraffe** [comment]
The more button is enough for me, since I never noticed it. I can leave this open if you'd like for if you add it to the popup, but my own issue is solved.
If you do add it to the popup, maybe it would be cool if you could select what writing systems are shown on the popup?
