### ISSUE TITLE
allow deep linking of POS

### ISSUE THREAD

**Issue by fuddl** [cubedhuang/nimi.li#12]
I'd like to make a deep link:

https://nimi.li/ale#adjective
https://nimi.li/ale#noun
https://nimi.li/ale#number

It should work like on marriam webster:
https://www.merriam-webster.com/dictionary/everything#dictionary-entry-2

but the section should be visually highlighted somehow:

![](https://github.com/cubedhuang/sona-nimi/assets/842548/45a7c286-6251-479f-a4bc-aa2c4cbab5fc)

Each POS will need an id

```diff
  <div class="mt-2 svelte-1ii88w7">
-     <p class="mt-1 svelte-1ii88w7"><span class="faded shrink-0 svelte-1ii88w7">ADJECTIVE</span> all; abundant, countless, bountiful, every, plentiful </p>
+     <p id="adjective" class="mt-1 svelte-1ii88w7"><span class="faded shrink-0 svelte-1ii88w7">ADJECTIVE</span> all; abundant, countless, bountiful, every, plentiful </p>
-     <p class="mt-1 svelte-1ii88w7"><span class="faded shrink-0 svelte-1ii88w7">NOUN</span> abundance, everything, life, universe </p>
+     <p id="noun" class="mt-1 svelte-1ii88w7"><span class="faded shrink-0 svelte-1ii88w7">NOUN</span> abundance, everything, life, universe </p>
-     <p class="mt-1 svelte-1ii88w7"><span class="faded shrink-0 svelte-1ii88w7">NOUN</span> abundance, everything, life, universe </p>
+     <p id="number" class="mt-1 svelte-1ii88w7"><span class="faded shrink-0 svelte-1ii88w7">NUMBER</span>
       100 </p>
  </div>
```

and some css for highlighting:

```css 
.mt-1:target {
  background: highlight;
  padding-left: .3em;
}
```

**Comment by cubedhuang** [comment]
thanks for the issue, but this is not planned

generally in toki pona, splitting content words into parts of speech like nouns, verbs, and adjectives isn't common and is only really found in pu, which is a decade old now. "ale" represents the idea of "everything" no matter if it's used in the place of a noun, verb, or modifier; there's no real use in having separate adjective and noun definitions

the only reason pu definitions are featured is for historical reasons/completeness. adding this feature would make pu's analysis seem more prominent than it descriptively is today, and i wouldn't want to promote the usage of it by adding deep links
