### ISSUE TITLE
The website broke...

### ISSUE THREAD

**Issue by elithepidude** [cubedhuang/nimi.li#15]
![Screenshot 2024-03-03 201835](https://github.com/cubedhuang/sona-nimi/assets/102700428/39890d67-c8d6-4b6f-9e84-79470f58fa05)

The CSS broke and the buttons don't work.

Without font extension (I like to use an extension to use fonts, but indeed, it's very similar to the top image):

![Screenshot 2024-03-03 202416](https://github.com/cubedhuang/sona-nimi/assets/102700428/98bf9ee8-c595-48b9-a043-15d77552b927)

**Comment by cubedhuang** [comment]
interesting

i haven't experienced this -- it may be because of the network connection that you're on causing faulty caching or preventing the css and js from loading that's causing this. i don't think this is possible to fix on my end
