### ISSUE TITLE
Add automatic light/dark themes? 

### ISSUE THREAD

**Issue by stvmln86** [cubedhuang/nimi.li#19]
Would it be possible to use [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) to automatically set the website's light/dark theme based on user settings, instead of having to manually hit the theme button?

**Comment by cubedhuang** [comment]
I'm already doing this!

https://github.com/cubedhuang/sona-nimi/blob/f6c3f3b5324e3e2efacbadb7255d2d2afccbbc32/src/app.html#L41C3-L52C12

https://github.com/cubedhuang/sona-nimi/blob/f6c3f3b5324e3e2efacbadb7255d2d2afccbbc32/src/lib/stores.ts#L34C1-L37C3

**Comment by cubedhuang** [comment]
Looking at this, I realized that there is currently no way to use system preferences only; i.e. if your device changes light/dark mode at different times of day, it'll be remember the state that you first visited the website in and only load that state from that point on. I'll add this setting and make it the default option, with light/dark as overrides instead.

**Comment by stvmln86** [comment]
Thank you!
