### ISSUE TITLE
lipu pi kulupu nimi o pana e nasin tawa lipu pi jan Sonja

### ISSUE THREAD

**Issue by tbodt** [cubedhuang/nimi.li#5]
lipu http://tokipona.org/compounds.txt li toki e ni a: sina pali e ijo kepeken lipu ni la o pana e nasin tawa lipu

> If you use this data in your project, please provide a link back to this file. 

ilo ni o ni

**Comment by cubedhuang** [comment]
a tenpo pini la sona ni li lon lipu "sona".

mi lukin e ni la mi pana e nasin tawa lipu lon lipu pi kulupu nimi kin
