### ISSUE TITLE
There's new words in Fairfax Pona

### ISSUE THREAD

**Issue by elithepidude** [cubedhuang/nimi.li#6]
There's a lot of new toki pona words (as well as symbols for words that didn't have a symbol yet) in Fairfax Pona, I think this might need an update to add them.
![Web capture_19-4-2023_134532_www kreativekorp com](https://user-images.githubusercontent.com/102700428/233172074-ceb44327-53d9-4521-8d74-cb407d95a9a4.jpeg)

**Comment by cubedhuang** [comment]
Apologies for not seeing this! I saw these symbols recently, but as nimi.li is a mirror of Linku's data, I'm planning on updating these when Linku's 2023 update is done

**Comment by elithepidude** [comment]
Oki doki! :3
